name: Matcha Stock Check

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  check-stock:
    runs-on: ubuntu-latest

    env:
      MARUKYU_USER: ${{ secrets.MARUKYU_USER }}
      MARUKYU_PASS: ${{ secrets.MARUKYU_PASS }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run matcha restock tracker
        run: python tracker.py
